### ISSUE TITLE
Paramaterized render fragments for different endpoint states

### ISSUE THREAD

**Issue by benlongo** [Jcparkyn/Phetch#1]
It could be nice (not sure) to have different `RenderFragment`s for each endpoint state.
For example, the sample given in the readme:
```
<UseEndpoint Endpoint="isEvenEndpoint" Arg="3" Context="query">
    @if (query.IsError) {
        <p><em>Something went wrong!</em></p>
    } else if (query.IsLoading) {
        <p><em>Loading...</em></p>
    } else if (query.HasData) {
        <b>The number is @(query.Data ? "even" : "odd")</b>
    }
</UseEndpoint>
```

could potentially be written as 
```
<UseEndpoint Endpoint="isEventEndpoint" Arg="3">
    <Loading>
        <p><em>Loading...</em></p>
    </Loading>
    <ErrorTemplate Context="error">
        @* ... *@
    </ErrorTemplate >
    <Loaded Context="Data">
         @* ... *@
    </Loaded>
</UseEndpoint>
```

The ability to default some of those fragments could also be useful.

**Comment by Jcparkyn** [comment]
Thanks for making an issue! I agree that your syntax is more user-friendly in a lot of cases, but the reasons I haven't added this option (yet?) are:
- The various possible states (uninitialized, loading, fetching, error, hasData, etc) aren't actually mutually exclusive, so the order they are written will often matter. E.g., a query can be both `HasData` and `IsFetching` at the same time. If I implement `<ErrorTemplate/>` etc as child `RenderFragments`, it's not possible for users to specify which one takes precedence.
- If each `RenderFragment` only receives the relevant data (e.g. `ErrorTemplate` receives `query.Error`, it's not possible for users to access other properties or methods on the query. For example, a common pattern is to have a "retry" button if there's an error, which would need to call `query.Refetch()`. The obvious solution here is to just pass the whole query to each `RenderFragment`, but then a lot of the benefits of this syntax are removed.
- The original syntax provides quite a lot more flexibility in the way the query is used, e.g., it's possible to combine with `switch` expressions or other C# features.
- Even though it's a lot more "Blazor-ish" and perhaps more intuitive, I can't think of any significant upsides to this syntax that would outweigh the limitations.

There's definitely an argument to be made that it'd be good to have this syntax as an additional option, but then I worry that a lot of users would hit its limitations quite quickly, and end up needing to re-write their code in the "original" syntax. This would be worse if I made the new syntax the "recommended" way, because some users might not even realize the other syntax exists.

I'm definitely interested in hearing any counter-arguments, and you're not the first person to suggest this so there's obviously something to it 😃.

**Comment by benlongo** [comment]
I agree that such an API would be too limiting as it doesn't allow handling all the interesting states of the query. Nullability narrowing is significantly better as you can get to the query states that your particular component cares about with boolean logic and the compiler will ensure you've done the necessary checks to access either the error or the data. 

I also agree that adding such an API would lead users down the wrong path, and probably suggest the wrong mental model for the query state machine as I had when I wrote the original issue. 

Your argument aligns with https://tkdodo.eu/blog/status-checks-in-react-query as well.
