### ISSUE TITLE
ParameterlessEndpoint keeps being unitialized

### ISSUE THREAD

**Issue by jardvanroest** [Jcparkyn/Phetch#2]
Hi, when I use a parameterless endpoint, it doesn't initialize. Using Endpoint instead, with an argument that doesn't get used fixes the issue for now, but is of course not the way this should be done.

My API implementation:
`
public class Api
{
    private readonly ILoggingBroker loggingBroker;
    private readonly IUserViewService userViewService;

    public Api(ILoggingBroker loggingBroker, IUserViewService userViewService)
    {
        this.loggingBroker = loggingBroker;
        this.userViewService = userViewService;

        var defaultOptions = new EndpointOptions()
        {
            DefaultStaleTime = TimeSpan.FromSeconds(60),
            RetryHandler = RetryHandler.Simple(1),
            OnFailure = e => Console.WriteLine(e.Exception.StackTrace),
        };

        GetUserViews = new(
            async (cancellationToken) => (await this.userViewService.RetrieveAllUsersAsync()),
            options: defaultOptions
        );
    }

    public ParameterlessEndpoint<IEnumerable<UserView>> GetUserViews { get; }
`

My component:

`
@inject Api Api;

<UseEndpoint Endpoint="Api.GetUserViews" Context="query">
    <Condition Evaluation="@(query.HasData)">
        <Match>
            <p>Users retrieved</p>
        </Match>
    </Condition>
    
    <Condition Evaluation="@(query.IsLoading)">
        <Match>
            <p>Loading...</p>
        </Match>
    </Condition>
    
    <Condition Evaluation="@(query.IsError)">
        <Match>
            <p>@query.Error?.Message</p>
        </Match>
    </Condition>
    
    <p>Query: @query</p>
    <p>@query.HasData</p>
    <p>@query.IsLoading</p>
    <p>@query.IsError</p>
    <p>@query.Data</p>
    <p>Uninitialized: @query.IsUninitialized</p> 
</UseEndpoint>

@code {

}
`

**Comment by Jcparkyn** [comment]
I think you missed some of your component code in the description (e.g. where is "query" defined?) so I can't tell exactly what's going on, but:

- If you're creating the query with `endpoint.Use(...)`, you'll need to explicitly call `query.Fetch()` to make it initialize. This is by design (to enable use-cases where people _don't_ want it to fetch immediately), but I agree that it's not the most intuitive.
- If you're using `<UseEndpoint/>`, you should replace it with `<UseParameterlessEndpoint/>`, which will fetch it automatically without needing an Arg.

I'll definitely make sure to update the doc comment for the `ParameterlessEndpoint.Use()` so that this is more clear, and maybe consider changing the default behaviour in the next update. It actually used to initialize by default until I decided it was cleaner not to, but the library has changed a lot since then.

**Comment by Jcparkyn** [comment]
Also a very tiny note which is unrelated to this issue:

Since you're not using the CancellationToken, you can replace
```cs
    GetUserViews = new(
        async (cancellationToken) => (await this.userViewService.RetrieveAllUsersAsync()),
        options: defaultOptions
    );
```
with
```cs
    GetUserViews = new(
        userViewService.RetrieveAllUsersAsync,
        options: defaultOptions
    );
```
which is functionally equivalent.

**Comment by jardvanroest** [comment]
Hi Jcparkyn,

I was using `<UseEndpoint />` instead of `<UseParameterlessEndpoint />`, so that's where I went wrong. Would be nice to see that explained more clearly in the documentation. 

Thanks for your help!
